### ISSUE TITLE
 Previous task | Tasklist FS#1780 - Polar import gives strange result with Architect data 

### ISSUE THREAD

**Issue by dominig** [seandepagnier/weather_routing_pi#20] opened 2015-06-23 07:32 UTC
Version:
OS
OpenSUSE 13.1
OpenCPN
Stable 4.0
Weather routing Plugin
SHA 9a19a5aa45b3eabe70ebf47798392bc8cc300e9f
date 10 May 2015

I have converted the data provided by Finot-Conq for may boat in a .pol file.
While the Polar plugin takes that file perfectly,
Weather routing create a very strange diagram which let to beleive that it will not work that well.
(see files joined).
![weatherroutingpolarbug1](https://cloud.githubusercontent.com/assets/1193120/8300958/857c63ce-198a-11e5-9314-e9e9decb92ce.png)

**Comment by seandepagnier** [comment] 2015-06-23 10:18
could you post the file you have loaded?  Maybe it's a bug in the plugin.

**Comment by dominig** [comment] 2015-06-23 11:57
Here it is.
'as only "image" file are supported I have renamed the file from .pol to .png
![oceanis31-finot-conq](https://cloud.githubusercontent.com/assets/1193120/8305465/b46e1b9e-19af-11e5-9dfb-a6f88513326b.png)

**Comment by rgleason** [comment] 2015-06-23 22:13
dominig,  I believe you can fix it by making sure there is [CR][LF} at the end of each line, otherwise the routine seems to start back at the origin again.  I think Sean can make the plugin smarter so that it will inject a badly formed pol file, but it is far better to have the pol properly configured with the right delimiters.

**Comment by rgleason** [comment] 2015-06-23 22:32
I believe you could paste the lines into excel and export as .csv and that might fix the end of line delimiters. I tried to change it in notepad++ and have not figured out how to do it yet.

**Comment by dominig** [comment] 2015-06-24 07:33
Rick,
    
    Sorry it does not solve the issue. 
    As I work on Linux I only have a [LF] by default but I have
    converted the file to Dos and the result is the same.
    
    In any case supporting Linux text file format would be nice.
    Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG
    Le 24/06/2015 00:13, Rick Gleason a
      écrit :
    
    
      dominig, I believe you can fix it by making sure there is
        [CR][LF} at the end of each line, otherwise the routine seems to
        start back at the origin again. I think Sean can make the plugin
        smarter so that it will inject a badly formed pol file, but it
        is far better to have the pol properly configured with the right
        delimiters.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by dominig** [comment] 2015-06-24 07:35
Rick,
    
    under Linux there is a tool unix2dos which does that.
    But that is not the source of the bug :-)
    
    Sorry.
    Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG
    Le 24/06/2015 00:32, Rick Gleason a
      écrit :
    
    
      I believe you could paste the lines into excel and export as
        .csv and that might fix the end of line delimiters. I tried to
        change it in notepad++ and have not figured out how to do it
        yet.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by rgleason** [comment] 2015-06-24 10:51
Sorry, I was wrong about that. What I've tried using Notepad++ search and replace.
1. Replace LF with CR LF at EOL
2. Replace ";" semicolon with [space]
3. Count the number of entries to make sure they are the same as the number of wind speeds.

Finally noticed that I had fixed it so far as the first two or three polar values (tacking angles) and there is something about the following lines that is mal formed. I think it is the number of speed entries.
And will check again.

**Comment by seandepagnier** [comment] 2015-06-25 10:02
The problem is in your polar file it lists a speed of zero at the
following wind directions:
55, 65, 75, 85, 95, 105, 115, 125, 130, 140, 145, 155, 165, 175

So there is no bug in the plugin as it was working correctly.

If you delete these lines from the polar file it should help.

Sean

**Comment by rgleason** [comment] 2015-06-25 11:42
Thanks, Sean. Just learned something about polars. I wonder if this happens often, the zeros for high wind speeds. I suppose if a high wind speed had zeros at all angles, that windspeed column could be stripped, starting with the highest wind speed and stopping when there is any value >0 in a wind speed column.   However the polar should be well formed and I guess the rule might be 
"No wind speed columns with all zeros at the high wind speed end.

Does that also apply to the low wind speed side? Delete the columns when the entire column is zeros?

**Comment by rgleason** [comment] 2015-06-25 11:59
If the pllugin corrects or improves the polar internally, would there be a reasonable way to be able to save it back out?

**Comment by dominig** [comment] 2015-07-02 15:12
Thanks. I found the error.
The Polar Plug, when you load the data from the architect fills with 0 what ever is unknown and save the zero line.
I will raise the bug on their side.
Thanks.

**Comment by rgleason** [comment] 2015-09-12 04:14
Polar_pi will not import incorrectly formatted files with all zeros in a line and then export the corrected file so that weather_routing will read it. I would be nice if weather_routing would do the same, or at least correct it internally so that the routing would work.

**Comment by rgleason** [comment] 2015-09-16 23:40
This has been fixed. Please close.

**Comment by dominig** [comment] 2015-09-17 14:58
Hello,
    
    I have requested the bug closure on the tracker.
    Dominig ar Foll
Senior Software Architect
Open Source Technology Centre
Intel SSG
    Le 17/09/2015 01:40, Rick Gleason a
      écrit :
    
    
      This has been fixed. Please close.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by rgleason** [comment] 2015-09-17 16:30
dominig,
Thank you.  I am learning this github system. Normally if I opened the issue I would have a way of closing it at the very bottom with "Close this issue" next to "Comment". 

Can you see if you have access to close iit  since you opened it?
Thanks. Sorry for the bother.

**Closed** 2015-09-17 16:41 UTC
