### ISSUE TITLE
crashes opencpn with land detection switched on 

### ISSUE THREAD

**Issue by barrymac** [seandepagnier/weather_routing_pi#21] opened 2015-09-03 21:42 UTC
Appears to be quite reliably reproducible with versions (from fork and main line open cpn) with versions 4.0.0 , 4.718, 4.818 on both arm and x86 

I built using wx widgets 3.0

**Comment by seandepagnier** [comment] 2015-09-07 15:44
I think the problem is you don't have any gshhs data installed.  Obviously it shouldn't crash so we should fix this.  If you can confirm this is the cause it would be great.

Otherwise, you are going to need to post a backtrace because it works perfectly for me.

**Comment by rgleason** [comment] 2015-09-07 16:01
find high res version  here,  follow the link  http://opencpn.org/ocpn/chart_sources
at the top   High Resolution Background Map .
There is a low res version too.
Sean maybe the error message should make reference?  (but it might change when O goes to GSHHG).

http://www.earthmodels.org/data-and-tools/coastlines/gshhs
http://www.idlcoyote.com/map_tips/gshhs.html

**Comment by barrymac** [comment] 2015-09-07 16:15
I using cm93 vector charts. I will try adding GSHHG and see how it goes. Will try to figure out how to provide a backtrace. I'm not experienced with C++ builds, I'm guessing it's a cmake flag to enable this or it's on by default?

**Comment by rgleason** [comment] 2015-09-07 23:04
Barry Mac - Weather Routing depends on GSHHG for identifying landmass! Just get it installed first and try wxrouting

**Comment by seandepagnier** [comment] 2015-09-08 03:32
I think it crashes without the world coastline data (you must see a
world map without any charts installed) which I really should fix by
giving the user a warning instead of crashing.

Let me know if it crashes ones the charts are installed.

**Comment by barrymac** [comment] 2015-09-08 19:00
I had the impression at first that the cm93 or built in low res coastline would work. In any case it works brilliantly with GSHHS installed. This plugin takes opencpn to another level! 

It doesn't work with GSHHG @rgleason that I tried first though. Here is the backtrace in case that helps in any case.

*** opencpn (wxWidgets 3.0.2) crashed ***, see backtrace!
opencpn: Fatal IO error 11 (Resource temporarily unavailable) on X server :1.
0x556e8b39359d in wxCrashPrint::Report() at ??:0
0x7f35d4e5a33e in  at ??:0
0x7f35ce7bab30 in  at ??:0
0x7f35ce46ebda in fseek at ??:0
0x556e8b27d41b in GshhsPolyCell::ReadPolygonFile() at ??:0
0x556e8b27dba4 in GshhsPolyCell::GshhsPolyCell(_IO_FILE*, int, int, PolygonFileHeader*) at ??:0
0x556e8b27e309 in GshhsPolyReader::crossing1(wxLineF) at ??:0
0x556e8b27e75a in gshhsCrossesLand(double, double, double, double) at ??:0
0x7f35bcb62c34 in Position::CrossesLand(double, double) at ??:0
0x7f35bcb620d6 in Position::Propagate(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f35bcb67a76 in IsoRoute::Propagate(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f35bcb6821d in IsoChron::PropagateIntoList(std::list<IsoRoute*, std::allocator<IsoRoute*> >&, RouteMapConfiguration&) at ??:0
0x7f35bcb69603 in RouteMap::Propagate() at ??:0
0x7f35bcb6d434 in RouteMapOverlayThread::Entry() at ??:0
0x7f35d4e57e72 in wxThread::CallEntry() at ??:0
0x7f35d4e58737 in  at ??:0
0x7f35ce7b14bc in  at ??:0
0x7f35ce4ef1cd in clone at ??:0

**Comment by rgleason** [comment] 2015-09-08 22:30
Very very sorry  Barrymac, I meant GSSHS!!

**Comment by rgleason** [comment] 2015-12-03 02:02
Sean can this be closed now?
Maybe wxroute could check for GSHHS and put up a prompt if not found?

**Comment by rgleason** [comment] 2016-06-16 19:54
This can be closed now Sean. I can't close it.  mbouyer should make a separate issue.

**Closed** 2016-06-16 22:42 UTC
